# Generated by Django 4.2.4 on 2023-10-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festtb',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
